import { JWT } from 'google-auth-library';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import moment from 'moment';

const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: '',
    key: '',
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

const SPREADSHEET_ID = '';

export async function updateReport() {
    // 1. Update Google Spreadsheet with messages list
    const sheet = await getSheet();
    // await sheet.clear();
    const sheetRowsData = (await sheet.getRows()).map((row: any) => row._rawData);
    console.log('Sheet Rows:', sheetRowsData.length);

    const calls = [];

    console.log('Calls:', calls.length);
    const filteredCalls = calls.filter(call => call.id && !sheetRowsData.find(row => row[0] === call.id));
    console.log('Filtered Calls:', filteredCalls.length);

    await sheet.setHeaderRow([
        'ID',
        'Transcript',
        'Summary',
        'Duration',
        'Sentiment',
        'Is Successful',
        'Completion Rating',
        'Category',
        'Recording URL',
        'Start Timestamp',
        'End Timestamp',
    ]);
    const rows = filteredCalls.map(call => {
        const item = {
            ID: call.id,
            Transcript: call.transcript,
            Summary: call.summary,
            Duration: call.duration_ms,
            Sentiment: call.sentiment,
            'Is Successful': call.is_successful,
            'Completion Rating': call.completion_rating,
            Category: call.category,
            'Recording URL': call.recording_url,
            'Start Timestamp': moment(call.start_timestamp).format('YYYY-MM-DD HH:mm:ss'),
            'End Timestamp': moment(call.end_timestamp).format('YYYY-MM-DD HH:mm:ss'),
        };
        return item;
    });
    await sheet.addRows(rows);
    return;
}

export async function getSheet() {
    const doc = new GoogleSpreadsheet(SPREADSHEET_ID, serviceAccountAuth);
    await doc.loadInfo();
    const sheet = doc.sheetsByIndex[0];
    return sheet;
}
